### ISSUE TITLE
Does not work when posting files with the request

### ISSUE THREAD

**Issue by gavinharriss** [SamStrong/WebAPI.HMAC#2]
Seems to be an issue with `httpContent.ReadAsByteArrayAsync()` inside `ComputeHash` helper function when a file is attached as content.

Full details here:

http://stackoverflow.com/questions/38904954/httpcontent-readasbytearrayasync-fails-without-error-inside-delegatinghandler

**Comment by SamStrong** [comment]
I've just been having a look at this. I can get it to work with arrays of 40,000 bytes (attached as a file), but it fails as you describe for arrays of 50,000 bytes.

**Comment by SamStrong** [comment]
Okay I think I've got a fix...

Having tested this with various sizes of file, I found the issue arose when files got around the 50,000 byte mark.

This post provided a solution: HttpContent.ReadAsStringAsync causes request to hang (or other strange behaviours).

If you replace erroring line in HMACHelper (line 66):

`var content = await httpContent.ReadAsByteArrayAsync();`

with this:

`var ms = new MemoryStream();`
`await httpContent.CopyToAsync(ms);`
`ms.Seek(0, SeekOrigin.Begin);`

`var content = ms.ToArray();`

It should stop hanging.

**Comment by gavinharriss** [comment]
Thanks Sam, that seems to have resolved the issue. Thanks so much for taking the time to look into this - it's very much appreciated!

**Comment by gavinharriss** [comment]
Sorry, I was a bit too quick to close this. The issue just moves to `await httpContent.CopyToAsync(ms)` for me now.

**Comment by SamStrong** [comment]
Would you be able to provide me with a copy of the file you're using to test it?

**Comment by gavinharriss** [comment]
Attached is an example file I'm uploading inside the attached zip (as GitHib won't allow me to attach an xml file directly).

[ExampleFileInside.zip](https://github.com/SamStrong/WebAPI.HMAC/files/417643/ExampleFileInside.zip)

And here some code relevant in my solution (in case I've been a muppet by doing something silly):

```
private string AppId = ConfigurationManager.AppSettings["API:AppId"];
private string SecretKey = ConfigurationManager.AppSettings["API:SecretKey"];
private int RequestTimeoutSecs = Convert.ToInt32(ConfigurationManager.AppSettings["API:TimeoutSecs"]);

private HttpClient HttpClient
{
    get
    {
        var client = new HMACHttpClient(AppId, SecretKey);
        client.Timeout = new TimeSpan(0, 0, RequestTimeoutSecs);
        return client;
    }
}

private FileOutputViewModel GetApiOutput(Uri apiResource, string filename, byte[] file, IDictionary<string, string> extraParameters)
{
    FileOutputViewModel result = new FileOutputViewModel();
            
    if (file != null)
    {
        using (var content = new MultipartFormDataContent())
        {
            if (extraParameters != null)
            {
                foreach (var param in extraParameters)
                {
                    content.Add(new StringContent(param.Value), param.Key);
                }
            }
                    
            var fileContent = new ByteArrayContent(file);
            fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment")
            {
                FileName = filename
            };
            content.Add(fileContent);

            var response = HttpClient.PostAsync(apiResource.ToString(), content).Result;

            result.Output = JsonConvert.DeserializeObject(response.Content.ReadAsStringAsync().Result);

            result.Filename = Path.GetFileName(filename);
        }
    }

    return result;
}
```

**Comment by SamStrong** [comment]
I'll try and take a look after work this evening.

**Comment by gavinharriss** [comment]
Thanks for that, so much appreciated.

I'm sure I saw it work initially (why I marked it as resolved), but maybe I accidentally picked a really small file.

**Comment by SamStrong** [comment]
Okay, it works for me (at least it doesn't hang the number of bytes I get out the end is the same). I'm just testing it with a console app though.

Here's how I'm attaching the file:
```
const string appId = "4d53bce03ec34c0a911182d4c228ee6c";
const string apiKey = "A93reRTUJHsCuQSHR+L3GxqOJyDmQpCgps102ciuabc=";

var client = new HMACHttpClient(appId, apiKey);

var fileStream = new FileStream(@"C:\Users\Sam\Downloads\10.xml", FileMode.Open, FileAccess.Read);
byte[] bytes = new byte[fileStream.Length];
fileStream.Read(bytes, 0, bytes.Length);

var requestContent = new MultipartFormDataContent();

var fileContent = new ByteArrayContent(bytes);

requestContent.Add(fileContent, "file", "File Name");

var response = await client.PostAsync("http://localhost:2757/api/orders/upload", requestContent);
```

Here's my action method for receiving the file:
```
[HttpPost, Route("upload")]
public async Task<IHttpActionResult> Upload()
{
    if (!Request.Content.IsMimeMultipartContent())
        throw new HttpResponseException(HttpStatusCode.UnsupportedMediaType);

    var provider = new MultipartMemoryStreamProvider();

    Request.Content.LoadIntoBufferAsync().Wait();
            
    await Request.Content.ReadAsMultipartAsync(provider);
    foreach (var file in provider.Contents)
    {
        var filename = file.Headers.ContentDisposition.FileName.Trim('\"');
        var buffer = await file.ReadAsByteArrayAsync();

        // Stick something in here that you can break on.
    }

    return Ok();
}
```

It's a basic example so please let me know if there's anything that you're doing that I'm not taking into account.

**Comment by gavinharriss** [comment]
Thanks for investigating! Interesting...

I now realise why it worked first time, then failed subsequently for me. Seems the issue occurs when when multiple content types are added.

If I comment out the `content.Add(new StringContent(param.Value), param.Key)` line from my code above, everything works fine. Seems there's an issue adding both `StringContent` and `ByteArrayContent` to the same `MultipartFormDataContent` item.

I'll have a play and see if I can work around this somehow. Maybe I'm adding the extra data incorrectly alongside the file.

**Comment by SamStrong** [comment]
Let me know if you find a way to make it work. When I get time, I'll get these fixes into the main codebase and update the NuGet package. It'd be good to get your GET request fix in too.

**Comment by gavinharriss** [comment]
Been playing around with this on/off and not made any progress.

Posted another question on stackoverflow in case anyone's come across this issue before:
http://stackoverflow.com/q/38966981/250254

Btw - thanks for making this code publicly available, it's really helped me a lot. Was working wonderfully until I started attaching files.

**Comment by gavinharriss** [comment]
Just to give you an update... been trying all sorts of potential workarounds without any joy, so decided to post to MSDN forums as feels like a bug with .NET framework itself.

Encouragingly, seems they're taking a look at it - https://social.msdn.microsoft.com/Forums/vstudio/en-US/55f5571d-fe94-4b68-b1d4-bfb91fd721dd/reading-httpcontent-bytes-fails-inside-delegatinghandler-when-multiple-content-types-present?forum=wcf

**Comment by gavinharriss** [comment]
Finally found a fix - seems the issue was caused by having an async method signature in the delegating handler - http://stackoverflow.com/a/39694191/250254

**Comment by SamStrong** [comment]
Sorry for the delay. Pull request merged.
